package converter

import (
	"regexp"
	"strings"
)

// ConvertToPallady converts to pallady
func ConvertToPallady(input string) string {
	if input == "" {
		return ""
	}

	result := removeMarks(input)
	result = makePallady(result)
	return result
}

// removeMarks removes the marks from the pinyin
func removeMarks(raw string) string {
	// define regular expression patterns for each marked vowel
	replacements := map[*regexp.Regexp]string{
		regexp.MustCompile(`[āáǎà]`): "a",
		regexp.MustCompile(`[ĀÁǍÀ]`): "A",
		regexp.MustCompile(`[ēéěè]`): "e",
		regexp.MustCompile(`[ĒÉĚÈ]`): "E",
		regexp.MustCompile(`[īíǐì]`): "i",
		regexp.MustCompile(`[ĪÍǏÌ]`): "I",
		regexp.MustCompile(`[ōóǒò]`): "o",
		regexp.MustCompile(`[ŌÓǑÒ]`): "O",
		regexp.MustCompile(`[ūúǔù]`): "u",
		regexp.MustCompile(`[ŪÚǓÙ]`): "U",
		regexp.MustCompile(`[ǖǘǚǜ]`): "ü",
	}

	// iterate over the map and replace each pattern in the string
	for re, rereplacements := range replacements {
		raw = re.ReplaceAllString(raw, rereplacements)
	}

	return raw
}

// processPallady6 converts the pinyin with length 6 to pallady
func processPallady6(raw string) string {
	pallady6 := map[string]string{
		"chuang": "чуан",
		"shuang": "шуан",
		"zhuang": "чжуан",
		"Chuang": "Чуан",
		"Shuang": "Шуан",
		"Zhuang": "Чжуан",
	}

	for k, v := range pallady6 {
		raw = strings.Replace(raw, k, v, -1)
	}

	return raw
}

// processPallady5 converts the pinyin with length 5 to pallady
func processPallady5(raw string) string {
	pallady5 := map[string]string{
		"chang": "чан",
		"cheng": "чэн",
		"chong": "чун",
		"chuai": "чуай",
		"chuan": "чуань",
		"diang": "дян",
		"guang": "гуан",
		"huang": "хуан",
		"jiong": "цзюн",
		"jiang": "цзян",
		"kuang": "куан",
		"liang": "лян",
		"niang": "нян",
		"piang": "пян",
		"qiong": "цюн",
		"qiang": "цян",
		"shang": "шан",
		"sheng": "шэн",
		"shuai": "шуай",
		"shuan": "шуань",
		"tiang": "тян",
		"xiong": "сюн",
		"xiang": "сян",
		"zhang": "чжан",
		"zheng": "чжэн",
		"zhong": "чжун",
		"zhuai": "чжуай",
		"zhuan": "чжуань",
		"Chang": "Чан",
		"Cheng": "Чэн",
		"Chong": "Чун",
		"Chuai": "Чуай",
		"Chuan": "Чуань",
		"Diang": "Дян",
		"Guang": "Гуан",
		"Huang": "Хуан",
		"Jiong": "Цзюн",
		"Jiang": "Цзян",
		"Kuang": "Куан",
		"Liang": "Лян",
		"Niang": "Нян",
		"Piang": "Пян",
		"Qiong": "Цюн",
		"Qiang": "Цян",
		"Shang": "Шан",
		"Sheng": "Шэн",
		"Shuai": "Шуай",
		"Shuan": "Шуань",
		"Tiang": "Тян",
		"Xiong": "Сюн",
		"Xiang": "Сян",
		"Zhang": "Чжан",
		"Zheng": "Чжэн",
		"Zhong": "Чжун",
		"Zhuai": "Чжуай",
		"Zhuan": "Чжуань",
	}

	for k, v := range pallady5 {
		raw = strings.Replace(raw, k, v, -1)
	}

	return raw
}

// processPallady4 converts the pinyin with length 4 to pallady
func processPallady4(raw string) string {
	pallady4 := map[string]string{
		"bang": "бан",
		"beng": "бэн",
		"bian": "бянь",
		"biao": "бяо",
		"bing": "бин",
		"cang": "цан",
		"ceng": "цэн",
		"cong": "цун",
		"cuan": "цуань",
		"chai": "чай",
		"chan": "чaнь",
		"chao": "чао",
		"chen": "чэнь",
		"chou": "чоу",
		"chua": "чуа",
		"chui": "чуй",
		"chun": "чунь",
		"chuo": "чо",
		"dang": "дан",
		"deng": "дэн",
		"dian": "дянь",
		"diao": "дяо",
		"ding": "дин",
		"dong": "дун",
		"duan": "дуань",
		"fang": "фан",
		"feng": "фэн",
		"fiao": "фяо",
		"gang": "ган",
		"geng": "гэн",
		"gong": "гун",
		"guai": "гуай",
		"guan": "гуань",
		"hang": "хан",
		"heng": "хэн",
		"hong": "хун",
		"huai": "хуай",
		"huan": "хуань",
		"jian": "цзянь",
		"jiao": "цзяо",
		"jing": "цзин",
		"juan": "цзюань",
		"kang": "кан",
		"keng": "кэн",
		"kong": "кун",
		"kuai": "куай",
		"kuan": "куань",
		"lang": "лан",
		"leng": "лэн",
		"lian": "лянь",
		"liao": "ляо",
		"ling": "лин",
		"long": "лун",
		"luan": "луань",
		"lüan": "люань",
		"lvan": "люань",
		"mang": "ман",
		"meng": "мэн",
		"mian": "мянь",
		"miao": "мяо",
		"ming": "мин",
		"nang": "нан",
		"neng": "нэн",
		"nian": "нянь",
		"niao": "няо",
		"ning": "нин",
		"nong": "нун",
		"nuan": "нуань",
		"pang": "пан",
		"peng": "пэн",
		"pian": "пянь",
		"piao": "пяо",
		"ping": "пин",
		"qian": "цянь",
		"qiao": "цяо",
		"qing": "цин",
		"quan": "цюань",
		"rang": "жан",
		"reng": "жэн",
		"rong": "жун",
		"ruan": "жуань",
		"sang": "сан",
		"seng": "сэн",
		"song": "сун",
		"suan": "суань",
		"shai": "шай",
		"shan": "шань",
		"shao": "шао",
		"shei": "шэй",
		"shen": "шэнь",
		"shou": "шоу",
		"shua": "шуа",
		"shui": "шуй",
		"shun": "шунь",
		"shuo": "шо",
		"tang": "тан",
		"teng": "тэн",
		"tian": "тянь",
		"tiao": "тяо",
		"ting": "тин",
		"tong": "тун",
		"tuan": "туань",
		"wang": "ван",
		"weng": "вэн",
		"xian": "сянь",
		"xiao": "сяо",
		"xing": "син",
		"xuan": "сюань",
		"yang": "ян",
		"ying": "ин",
		"yong": "юн",
		"yuan": "юань",
		"zang": "цзан",
		"zeng": "цзэн",
		"zong": "цзун",
		"zuan": "цзуань",
		"zhai": "чжай",
		"zhan": "чжань",
		"zhao": "чжао",
		"zhei": "чжэй",
		"zhen": "чжэнь",
		"zhou": "чжоу",
		"zhua": "чжуа",
		"zhui": "чжуй",
		"zhun": "чжунь",
		"zhuo": "чжо",
		"Bang": "Бан",
		"Beng": "Бэн",
		"Bian": "Бянь",
		"Biao": "Бяо",
		"Bing": "Бин",
		"Cang": "Цан",
		"Ceng": "Цэн",
		"Cong": "Цун",
		"Cuan": "Цуань",
		"Chai": "Чай",
		"Chan": "Чaнь",
		"Chao": "Чао",
		"Chen": "Чэнь",
		"Chou": "Чоу",
		"Chua": "Чуа",
		"Chui": "Чуй",
		"Chun": "Чунь",
		"Chuo": "Чо",
		"Dang": "Дан",
		"Deng": "Дэн",
		"Dian": "Дянь",
		"Diao": "Дяо",
		"Ding": "Дин",
		"Dong": "Дун",
		"Duan": "Дуань",
		"Fang": "Фан",
		"Feng": "Фэн",
		"Fiao": "Фяо",
		"Gang": "Ган",
		"Geng": "Гэн",
		"Gong": "Гун",
		"Guai": "Гуай",
		"Guan": "Гуань",
		"Hang": "Хан",
		"Heng": "Хэн",
		"Hong": "Хун",
		"Huai": "Хуай",
		"Huan": "Хуань",
		"Jian": "Цзянь",
		"Jiao": "Цзяо",
		"Jing": "Цзин",
		"Juan": "Цзюань",
		"Kang": "Кан",
		"Keng": "Кэн",
		"Kong": "Кун",
		"Kuai": "Куай",
		"Kuan": "Куань",
		"Lang": "Лан",
		"Leng": "Лэн",
		"Lian": "Лянь",
		"Liao": "Ляо",
		"Ling": "Лин",
		"Long": "Лун",
		"Luan": "Луань",
		"Lüan": "Люань",
		"Lvan": "Люань",
		"Mang": "Ман",
		"Meng": "Мэн",
		"Mian": "Мянь",
		"Miao": "Мяо",
		"Ming": "Мин",
		"Nang": "Нан",
		"Neng": "Нэн",
		"Nian": "Нянь",
		"Niao": "Няо",
		"Ning": "Нин",
		"Nong": "Нун",
		"Nuan": "Нуань",
		"Pang": "Пан",
		"Peng": "Пэн",
		"Pian": "Пянь",
		"Piao": "Пяо",
		"Ping": "Пин",
		"Qian": "Цянь",
		"Qiao": "Цяо",
		"Qing": "Цин",
		"Quan": "Цюань",
		"Rang": "Жан",
		"Reng": "Жэн",
		"Rong": "Жун",
		"Ruan": "Жуань",
		"Sang": "Сан",
		"Seng": "Сэн",
		"Song": "Сун",
		"Suan": "Суань",
		"Shai": "Шай",
		"Shan": "Шань",
		"Shao": "Шао",
		"Shei": "Шэй",
		"Shen": "Шэнь",
		"Shou": "Шоу",
		"Shua": "Шуа",
		"Shui": "Шуй",
		"Shun": "Шунь",
		"Shuo": "Шо",
		"Tang": "Тан",
		"Teng": "Тэн",
		"Tian": "Тянь",
		"Tiao": "Тяо",
		"Ting": "Тин",
		"Tong": "Тун",
		"Tuan": "Туань",
		"Wang": "Ван",
		"Weng": "Вэн",
		"Xian": "Сянь",
		"Xiao": "Сяо",
		"Xing": "Син",
		"Xuan": "Сюань",
		"Yang": "Ян",
		"Ying": "Ин",
		"Yong": "Юн",
		"Yuan": "Юань",
		"Zang": "Цзан",
		"Zeng": "Цзэн",
		"Zong": "Цзун",
		"Zuan": "Цзуань",
		"Zhai": "Чжай",
		"Zhan": "Чжань",
		"Zhao": "Чжао",
		"Zhei": "Чжэй",
		"Zhen": "Чжэнь",
		"Zhou": "Чжоу",
		"Zhua": "Чжуа",
		"Zhui": "Чжуй",
		"Zhun": "Чжунь",
		"Zhuo": "Чжо",
	}

	for k, v := range pallady4 {
		raw = strings.Replace(raw, k, v, -1)
	}

	return raw
}

// processPallady3 converts the pinyin with length 3 to pallady
func processPallady3(raw string) string {
	pallady3 := map[string]string{
		"ang": "ан",
		"bai": "бай",
		"ban": "бань",
		"bao": "бао",
		"bei": "бэй",
		"ben": "бэнь",
		"bie": "бе",
		"bin": "бинь",
		"cai": "цай",
		"can": "цань",
		"cao": "цао",
		"cei": "цэй",
		"cen": "цэнь",
		"cou": "цоу",
		"cui": "цуй",
		"cun": "цунь",
		"cuo": "цо",
		"cha": "ча",
		"che": "чэ",
		"chi": "чи",
		"chu": "чу",
		"dai": "дай",
		"dan": "дань",
		"dao": "дао",
		"dei": "дэй",
		"den": "дэнь",
		"dia": "дя",
		"die": "де",
		"diu": "дю",
		"dou": "доу",
		"dui": "дуй",
		"dun": "дунь",
		"duo": "до",
		"eng": "эн",
		"fan": "фань",
		"fei": "фэй",
		"fen": "фэнь",
		"fou": "фоу",
		"gai": "гай",
		"gan": "гань",
		"gao": "гао",
		"gei": "гэй",
		"gen": "гэнь",
		"gou": "гоу",
		"gua": "гуа",
		"gui": "гуй",
		"gun": "гунь",
		"guo": "го",
		"hai": "хай",
		"han": "хань",
		"hao": "хаo",
		"hei": "хэй",
		"hen": "хэнь",
		"hng": "хн",
		"hou": "хоу",
		"hua": "хуа",
		"hui": "хуэй",
		"hun": "хунь",
		"huo": "хo",
		"jia": "цзя",
		"jie": "цзе",
		"jin": "цзинь",
		"jiu": "цзю",
		"jue": "цзюэ",
		"jun": "цзюнь",
		"kai": "кай",
		"kan": "кань",
		"kao": "као",
		"kei": "кэй",
		"ken": "кэнь",
		"kou": "коу",
		"kua": "куа",
		"kui": "куй",
		"kun": "кунь",
		"kuo": "ко",
		"lai": "лай",
		"lan": "лань",
		"lao": "лао",
		"lei": "лэй",
		"lia": "ля",
		"lie": "ле",
		"lin": "линь",
		"liu": "лю",
		"lou": "лоу",
		"lüe": "люэ",
		"lve": "люэ",
		"lun": "лунь",
		"lün": "люнь",
		"lvn": "люнь",
		"luo": "ло",
		"mai": "май",
		"man": "мань",
		"mao": "мао",
		"mei": "мэй",
		"men": "мэнь",
		"mie": "ме",
		"min": "минь",
		"miu": "мю",
		"mou": "моу",
		"nai": "най",
		"nan": "нань",
		"nao": "нао",
		"nei": "нэй",
		"nen": "нэнь",
		"nia": "ня",
		"nie": "не",
		"nin": "нинь",
		"niu": "ню",
		"nou": "ноу",
		"nun": "нунь",
		"nüe": "нюэ",
		"nve": "нюэ",
		"nuo": "но",
		"pai": "пай",
		"pan": "пань",
		"pao": "пао",
		"pei": "пэй",
		"pen": "пэнь",
		"pie": "пе",
		"pin": "пинь",
		"pou": "поу",
		"qia": "ця",
		"qie": "це",
		"qin": "цинь",
		"qiu": "цю",
		"que": "цюэ",
		"qun": "цюнь",
		"ran": "жань",
		"rao": "жао",
		"rem": "жэм",
		"ren": "жэнь",
		"rou": "жоу",
		"rua": "жуа",
		"rui": "жуй",
		"run": "жунь",
		"ruo": "жо",
		"sai": "сай",
		"san": "сань",
		"sao": "сао",
		"sei": "сэй",
		"sen": "сэнь",
		"sou": "соу",
		"sui": "суй",
		"sun": "сунь",
		"suo": "со",
		"sha": "ша",
		"she": "шэ",
		"shi": "ши",
		"shu": "шу",
		"tai": "тай",
		"tan": "тань",
		"tao": "тао",
		"tei": "тэй",
		"ten": "тэнь",
		"tie": "те",
		"tou": "тоу",
		"tui": "туй",
		"tun": "тунь",
		"tuo": "то",
		"wai": "вай",
		"wan": "вань",
		"wao": "вао",
		"wei": "вэй",
		"wen": "вэнь",
		"xia": "ся",
		"xie": "се",
		"xin": "синь",
		"xiu": "сю",
		"xue": "сюэ",
		"xun": "сюнь",
		"yai": "яй",
		"yan": "янь",
		"yao": "яо",
		"yin": "инь",
		"you": "ю",
		"yue": "юэ",
		"yun": "юнь",
		"zai": "цзай",
		"zan": "цзань",
		"zao": "цзао",
		"zei": "цзэй",
		"zem": "цзэм",
		"zen": "цзэнь",
		"zou": "цзоу",
		"zui": "цзуй",
		"zun": "цзунь",
		"zuo": "цзо",
		"zha": "чжа",
		"zhe": "чжэ",
		"zhi": "чжи",
		"zhu": "чжу",
		"Ang": "Ан",
		"Bai": "Бай",
		"Ban": "Бань",
		"Bao": "Бао",
		"Bei": "Бэй",
		"Ben": "Бэнь",
		"Bie": "Бе",
		"Bin": "Бинь",
		"Cai": "Цай",
		"Can": "Цань",
		"Cao": "Цао",
		"Cei": "Цэй",
		"Cen": "Цэнь",
		"Cou": "Цоу",
		"Cui": "Цуй",
		"Cun": "Цунь",
		"Cuo": "Цо",
		"Cha": "Ча",
		"Che": "Чэ",
		"Chi": "Чи",
		"Chu": "Чу",
		"Dai": "Дай",
		"Dan": "Дань",
		"Dao": "Дао",
		"Dei": "Дэй",
		"Den": "Дэнь",
		"Dia": "Дя",
		"Die": "Де",
		"Diu": "Дю",
		"Dou": "Доу",
		"Dui": "Дуй",
		"Dun": "Дунь",
		"Duo": "До",
		"Eng": "Эн",
		"Fan": "Фань",
		"Fei": "Фэй",
		"Fen": "Фэнь",
		"Fou": "Фоу",
		"Gai": "Гай",
		"Gan": "Гань",
		"Gao": "Гао",
		"Gei": "Гэй",
		"Gen": "Гэнь",
		"Gou": "Гоу",
		"Gua": "Гуа",
		"Gui": "Гуй",
		"Gun": "Гунь",
		"Guo": "Го",
		"Hai": "Хай",
		"Han": "Хань",
		"Hao": "Хаo",
		"Hei": "Хэй",
		"Hen": "Хэнь",
		"Hng": "Хн",
		"Hou": "Хоу",
		"Hua": "Хуа",
		"Hui": "Хуэй",
		"Hun": "Хунь",
		"Huo": "Хo",
		"Jia": "Цзя",
		"Jie": "Цзе",
		"Jin": "Цзинь",
		"Jiu": "Цзю",
		"Jue": "Цзюэ",
		"Jun": "Цзюнь",
		"Kai": "Кай",
		"Kan": "Кань",
		"Kao": "Као",
		"Kei": "Кэй",
		"Ken": "Кэнь",
		"Kou": "Коу",
		"Kua": "Куа",
		"Kui": "Куй",
		"Kun": "Кунь",
		"Kuo": "Ко",
		"Lai": "Лай",
		"Lan": "Лань",
		"Lao": "Лао",
		"Lei": "Лэй",
		"Lia": "Ля",
		"Lie": "Ле",
		"Lin": "Линь",
		"Liu": "Лю",
		"Lou": "Лоу",
		"Lüe": "Люэ",
		"Lve": "Люэ",
		"Lun": "Лунь",
		"Lün": "Люнь",
		"Lvn": "Люнь",
		"Luo": "Ло",
		"Mai": "Май",
		"Man": "Мань",
		"Mao": "Мао",
		"Mei": "Мэй",
		"Men": "Мэнь",
		"Mie": "Ме",
		"Min": "Минь",
		"Miu": "Мю",
		"Mou": "Моу",
		"Nai": "Най",
		"Nan": "Нань",
		"Nao": "Нао",
		"Nei": "Нэй",
		"Nen": "Нэнь",
		"Nia": "Ня",
		"Nie": "Не",
		"Nin": "Нинь",
		"Niu": "Ню",
		"Nou": "Ноу",
		"Nun": "Нунь",
		"Nüe": "Нюэ",
		"Nve": "Нюэ",
		"Nuo": "Но",
		"Pai": "Пай",
		"Pan": "Пань",
		"Pao": "Пао",
		"Pei": "Пэй",
		"Pen": "Пэнь",
		"Pie": "Пе",
		"Pin": "Пинь",
		"Pou": "Поу",
		"Qia": "Ця",
		"Qie": "Це",
		"Qin": "Цинь",
		"Qiu": "Цю",
		"Que": "Цюэ",
		"Qun": "Цюнь",
		"Ran": "Жань",
		"Rao": "Жао",
		"Rem": "Жэм",
		"Ren": "Жэнь",
		"Rou": "Жоу",
		"Rua": "Жуа",
		"Rui": "Жуй",
		"Run": "Жунь",
		"Ruo": "Жо",
		"Sai": "Сай",
		"San": "Сань",
		"Sao": "Сао",
		"Sei": "Сэй",
		"Sen": "Сэнь",
		"Sou": "Соу",
		"Sui": "Суй",
		"Sun": "Сунь",
		"Suo": "Со",
		"Sha": "Ша",
		"She": "Шэ",
		"Shi": "Ши",
		"Shu": "Шу",
		"Tai": "Тай",
		"Tan": "Тань",
		"Tao": "Тао",
		"Tei": "Тэй",
		"Ten": "Тэнь",
		"Tie": "Те",
		"Tou": "Тоу",
		"Tui": "Туй",
		"Tun": "Тунь",
		"Tuo": "То",
		"Wai": "Вай",
		"Wan": "Вань",
		"Wao": "Вао",
		"Wei": "Вэй",
		"Wen": "Вэнь",
		"Xia": "Ся",
		"Xie": "Се",
		"Xin": "Синь",
		"Xiu": "Сю",
		"Xue": "Сюэ",
		"Xun": "Сюнь",
		"Yai": "Яй",
		"Yan": "Янь",
		"Yao": "Яо",
		"Yin": "Инь",
		"You": "Ю",
		"Yue": "Юэ",
		"Yun": "Юнь",
		"Zai": "Цзай",
		"Zan": "Цзань",
		"Zao": "Цзао",
		"Zei": "Цзэй",
		"Zem": "Цзэм",
		"Zen": "Цзэнь",
		"Zou": "Цзоу",
		"Zui": "Цзуй",
		"Zun": "Цзунь",
		"Zuo": "Цзо",
		"Zha": "Чжа",
		"Zhe": "Чжэ",
		"Zhi": "Чжи",
		"Zhu": "Чжу",
	}

	for k, v := range pallady3 {
		raw = strings.Replace(raw, k, v, -1)
	}

	return raw
}

// processPallady2 converts the pinyin with length 2 to pallady
func processPallady2(raw string) string {
	pallady2 := map[string]string{
		"ai": "ай",
		"an": "ань",
		"ao": "ао",
		"ba": "ба",
		"bi": "би",
		"bo": "бо",
		"bu": "бу",
		"ca": "ца",
		"ce": "цэ",
		"ci": "цы",
		"cu": "цу",
		"da": "да",
		"de": "дэ",
		"di": "ди",
		"du": "ду",
		"ei": "эй",
		"en": "энь",
		"er": "эр",
		"fa": "фа",
		"fo": "фо",
		"fu": "фу",
		"ga": "га",
		"ge": "гэ",
		"go": "го",
		"gu": "гу",
		"ha": "ха",
		"he": "хэ",
		"hm": "хм",
		"hu": "ху",
		"ji": "цзи",
		"ju": "цзюй",
		"ka": "ка",
		"ke": "кэ",
		"ku": "ку",
		"la": "ла",
		"le": "лэ",
		"li": "ли",
		"lo": "ло",
		"lu": "лу",
		"lü": "люй",
		"lv": "люй",
		"ma": "ма",
		"me": "мэ",
		"mi": "ми",
		"mm": "мм",
		"mo": "мо",
		"mu": "му",
		"na": "на",
		"ne": "нэ",
		"ng": "н",
		"ni": "ни",
		"nu": "ну",
		"nü": "нюй",
		"nv": "нюй",
		"ou": "оу",
		"pa": "па",
		"pi": "пи",
		"po": "по",
		"pu": "пу",
		"qi": "ци",
		"qu": "цюй",
		"re": "жэ",
		"ri": "жи",
		"ru": "жу",
		"sa": "са",
		"se": "сэ",
		"si": "сы",
		"su": "су",
		"ta": "та",
		"te": "тэ",
		"ti": "ти",
		"tu": "ту",
		"wa": "ва",
		"wo": "во",
		"wu": "у",
		"xi": "си",
		"xu": "сюй",
		"ya": "я",
		"ye": "е",
		"yi": "и",
		"yo": "йо",
		"yu": "юй",
		"za": "цза",
		"ze": "цзэ",
		"zi": "цзы",
		"zu": "цзу",
		"Ai": "Ай",
		"An": "Ань",
		"Ao": "Ао",
		"Ba": "Ба",
		"Bi": "Би",
		"Bo": "Бо",
		"Bu": "Бу",
		"Ca": "Ца",
		"Ce": "Цэ",
		"Ci": "Цы",
		"Cu": "Цу",
		"Da": "Да",
		"De": "Дэ",
		"Di": "Ди",
		"Du": "Ду",
		"Ei": "Эй",
		"En": "Энь",
		"Er": "Эр",
		"Fa": "Фа",
		"Fo": "Фо",
		"Fu": "Фу",
		"Ga": "Га",
		"Ge": "Гэ",
		"Go": "Го",
		"Gu": "Гу",
		"Ha": "Ха",
		"He": "Хэ",
		"Hm": "Хм",
		"Hu": "Ху",
		"Ji": "Цзи",
		"Ju": "Цзюй",
		"Ka": "Ка",
		"Ke": "Кэ",
		"Ku": "Ку",
		"La": "Ла",
		"Le": "Лэ",
		"Li": "Ли",
		"Lo": "Ло",
		"Lu": "Лу",
		"Lü": "Люй",
		"Lv": "Люй",
		"Ma": "Ма",
		"Me": "Мэ",
		"Mi": "Ми",
		"Mm": "Мм",
		"Mo": "Мо",
		"Mu": "Му",
		"Na": "На",
		"Ne": "Нэ",
		"Ng": "Н",
		"Ni": "Ни",
		"Nu": "Ну",
		"Nü": "Нюй",
		"Nv": "Нюй",
		"Ou": "Оу",
		"Pa": "Па",
		"Pi": "Пи",
		"Po": "По",
		"Pu": "Пу",
		"Qi": "Ци",
		"Qu": "Цюй",
		"Re": "Жэ",
		"Ri": "Жи",
		"Ru": "Жу",
		"Sa": "Са",
		"Se": "Сэ",
		"Si": "Сы",
		"Su": "Су",
		"Ta": "Та",
		"Te": "Тэ",
		"Ti": "Ти",
		"Tu": "Ту",
		"Wa": "Ва",
		"Wo": "Во",
		"Wu": "У",
		"Xi": "Си",
		"Xu": "Сюй",
		"Ya": "Я",
		"Ye": "Е",
		"Yi": "И",
		"Yo": "Йо",
		"Yu": "Юй",
		"Za": "Цза",
		"Ze": "Цзэ",
		"Zi": "Цзы",
		"Zu": "Цзу",
	}

	for k, v := range pallady2 {
		raw = strings.Replace(raw, k, v, -1)
	}

	return raw
}

// processPallady1 converts the pinyin with length 1 to pallady
func processPallady1(raw string) string {
	pallady1 := map[string]string{
		"a": "а",
		"e": "э",
		"m": "м",
		"n": "нь",
		"o": "о",
		"r": "р",
		"A": "А",
		"E": "Э",
		"M": "М",
		"N": "Нь",
		"O": "О",
		"R": "Р",
	}

	result := raw

	for k, v := range pallady1 {
		result = strings.Replace(result, k, v, -1)
	}

	return result
}

// makePallady converts the pinyin to pallady
func makePallady(raw string) string {
	result := processPallady6(raw)
	result = processPallady5(result)
	result = processPallady4(result)
	result = processPallady3(result)
	result = processPallady2(result)
	result = processPallady1(result)
	return result
}
